"""
Django settings for booking_system project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

# Base paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Core
SECRET_KEY = 'django-insecure-5+$(t4-+p%&92aned1z^!cz_)za2s+@(98b=kl6&7*cjls1ca&'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third‑party
    'rest_framework',
    # your apps
    'booking',
    'services',
    'staff',
    'clients',
    'notifications',
    'feedback',
    'reports',
    'configmgr',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'booking_system.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # app templates via APP_DIRS=True
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'booking_system.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# I18N / TZ
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Jamaica'
USE_I18N = True
USE_TZ = True

# Static
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================================================
# EMAIL: Real SMTP (Gmail) — LIVE FOR YOUR DEMO
# =====================================================
# WARNING: These hardcoded credentials are for demo. Do NOT keep secrets
# committed to a public repo. Move to environment variables for production.
#
# If you later want to switch back to console emails (dev-safe):
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# Test Gmail account (you provided these; assumed to be an App Password)
EMAIL_HOST_USER = 'test.acc51432@gmail.com'
EMAIL_HOST_PASSWORD = 'isdl djzq rkel wydt'  # App Password (spaces OK in app passwords)

# Default From
# You can put a nicer display name here; Gmail may show the account name.
DEFAULT_FROM_EMAIL = 'test.acc51432@gmail.com'

# =====================================================
# OPTIONAL (recommended later): Environment-driven SMTP
# =====================================================
# Keep this commented for now since you asked to run real emails immediately.
# When ready to remove hardcoded creds, uncomment and set env vars, then
# comment out the hardcoded block above.
#
# EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
# EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
# EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@hairbylasheka.local")