# Generated by Django 5.2.8 on 2025-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_clientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
