# Generated by Django 5.2.9 on 2025-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_clientprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
