# Generated by Django 5.2.8 on 2025-12-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status'),
        ('booking', '0007_alter_clientprofile_email'),
    ]

    operations = [
    ]
