# Generated by Django 5.2.9 on 2025-12-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status'),
        ('booking', '0008_clientprofile_phone'),
    ]

    operations = [
    ]
