# Generated by Django 5.2.8 on 2025-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
