# Generated by Django 5.2.9 on 2025-12-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, help_text='When the booking was cancelled (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Booking lifecycle status', max_length=10),
        ),
    ]
